/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AccountOutput {
  id: number
  name: string
  kind: string
  balance: number
  createdAt: number
}

export declare class Engine {
  constructor(path: string)
  createAccount(name: string, kind: string): number
  recordEntry(debitAccount: number, creditAccount: number, amountCents: number, description: string): number
  recordJournalEntry(description: string, legsJson: string): number
  listAccounts(): Array<AccountOutput>
  listAllTransactions(): Array<TransactionOutput>
  listJournalEntries(): Array<Array<TransactionOutput>>
  getExpenseSummary(startTs: number, endTs: number): ExpenseSummaryOutput
  validateLedger(): void
  forceFlush(): void
}

export declare class ExpenseSummaryOutput {
  totalDebits: number
  totalCredits: number
  net: number
  rowCount: number
  segmentsSkipped: number
}

export declare class TransactionOutput {
  id: number
  journalEntryId: number
  accountId: number
  amount: number
  transactionType: string
  timestamp: number
  description: string
  txHash: string
}
